/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentaspagar;

import Includes.Facturas;
import Includes.elementosFacturas;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author alijm
 */
public class FacturasTodas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Facturas
     */
    public FacturasTodas() {

        initComponents();
        new Facturas().obtenerProveedores(cbproveedores);
        this.tableFacturas.setModel(new Facturas().mostrar());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfechaini = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfechaven = new javax.swing.JFormattedTextField();
        rbdolares = new javax.swing.JRadioButton();
        rbeuros = new javax.swing.JRadioButton();
        rbotros = new javax.swing.JRadioButton();
        cbproveedores = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFacturas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventana de Facturas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones de Facturas"));

        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Ver Factura");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Agregar Productos a factura");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Pagar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones de facturas"));

        jLabel2.setText(" proveedor :");

        jLabel3.setText("Fecha Inicio : ");

        jLabel4.setText("Formato de pago:");

        try {
            txtfechaini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Fecha Vencimiento : ");

        try {
            txtfechaven.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        rbdolares.setBackground(new java.awt.Color(255, 255, 255));
        bgpago.add(rbdolares);
        rbdolares.setText("Dolares");

        rbeuros.setBackground(new java.awt.Color(255, 255, 255));
        bgpago.add(rbeuros);
        rbeuros.setText("Euros");

        rbotros.setBackground(new java.awt.Color(255, 255, 255));
        bgpago.add(rbotros);
        rbotros.setText("Otro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechaven, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(rbdolares)
                .addGap(18, 18, 18)
                .addComponent(rbeuros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbotros)
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(rbdolares)
                    .addComponent(rbeuros)
                    .addComponent(rbotros)
                    .addComponent(cbproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFacturas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   int filaSeleccionada = this.tableFacturas.getSelectedRow();
        if (!this.txtfechaini.getText().isEmpty() && !this.txtfechaven.getText().isEmpty() && (!this.rbdolares.isSelected() || !this.rbeuros.isSelected() || !this.rbotros.isSelected()) && this.cbproveedores.getSelectedIndex() > 0) {

            int nrofactura = Integer.parseInt(this.tableFacturas.getValueAt(filaSeleccionada, 0).toString());

            String proveedor = this.cbproveedores.getSelectedItem().toString();

            String fechaString1 = this.txtfechaini.getText();
            long fechaini = Date.parse(fechaString1);
            Date fechaDate1 = new Date(fechaini);

            String fechaString2 = this.txtfechaven.getText();
            long fechaven = Date.parse(fechaString2);
            Date fechaDate2 = new Date(fechaven);

            char formapago = 'D';
            if (this.rbdolares.isSelected()) {
                formapago = 'D';
            } else if (this.rbeuros.isSelected()) {
                formapago = 'E';
            } else if (this.rbotros.isSelected()) {
                formapago = 'O';
            }

            Facturas facturas = new Facturas(nrofactura, proveedor, fechaDate1, fechaDate2, formapago, 'A');

            int decision = JOptionPane.showConfirmDialog(null, "Esta seguro que desea Pagar esta factura?");

            if (decision == 0) {
                facturas.actualizarPagada();
                this.tableFacturas.setModel(facturas.mostrar());
            }

        }    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (!this.txtfechaini.getText().isEmpty() && !this.txtfechaven.getText().isEmpty() && (!this.rbdolares.isSelected() || !this.rbeuros.isSelected() || !this.rbotros.isSelected()) && this.cbproveedores.getSelectedIndex() > 0) {

            String proveedor = this.cbproveedores.getSelectedItem().toString();

            String fechaString1 = this.txtfechaini.getText();
            long fechaini = Date.parse(fechaString1);
            Date fechaDate1 = new Date(fechaini);

            String fechaString2 = this.txtfechaven.getText();
            long fechaven = Date.parse(fechaString2);
            Date fechaDate2 = new Date(fechaven);

            char formapago = 'D';
            if (this.rbdolares.isSelected()) {
                formapago = 'D';
            } else if (this.rbeuros.isSelected()) {
                formapago = 'E';
            } else if (this.rbotros.isSelected()) {
                formapago = 'O';
            }

            Facturas facturas = new Facturas(proveedor, fechaDate1, fechaDate2, formapago, 'A');
            facturas.agregar();
            this.tableFacturas.setModel(facturas.mostrar());

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.txtfechaini.setText("");
        this.txtfechaven.setText("");
        this.rbdolares.setSelected(false);
        this.rbeuros.setSelected(false);
        this.rbotros.setSelected(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = this.tableFacturas.getSelectedRow();
        if (!this.txtfechaini.getText().isEmpty() && !this.txtfechaven.getText().isEmpty() && (!this.rbdolares.isSelected() || !this.rbeuros.isSelected() || !this.rbotros.isSelected()) && this.cbproveedores.getSelectedIndex() > 0) {

            int nrofactura = Integer.parseInt(this.tableFacturas.getValueAt(filaSeleccionada, 0).toString());

            String proveedor = this.cbproveedores.getSelectedItem().toString();

            String fechaString1 = this.txtfechaini.getText();
            long fechaini = Date.parse(fechaString1);
            Date fechaDate1 = new Date(fechaini);

            String fechaString2 = this.txtfechaven.getText();
            long fechaven = Date.parse(fechaString2);
            Date fechaDate2 = new Date(fechaven);

            char formapago = 'D';
            if (this.rbdolares.isSelected()) {
                formapago = 'D';
            } else if (this.rbeuros.isSelected()) {
                formapago = 'E';
            } else if (this.rbotros.isSelected()) {
                formapago = 'O';
            }

            Facturas facturas = new Facturas(nrofactura, proveedor, fechaDate1, fechaDate2, formapago, 'A');

            int decision = JOptionPane.showConfirmDialog(null, "Esta seguro que desea actualizar esta factura?");

            if (decision == 0) {
                facturas.actualizar();
                this.tableFacturas.setModel(facturas.mostrar());
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int filaSeleccionada = this.tableFacturas.getSelectedRow();
        
        if (!this.txtfechaini.getText().isEmpty() && !this.txtfechaven.getText().isEmpty() && (!this.rbdolares.isSelected() || !this.rbeuros.isSelected() || !this.rbotros.isSelected()) && this.cbproveedores.getSelectedIndex() > 0) {

            int nrofactura = Integer.parseInt(this.tableFacturas.getValueAt(filaSeleccionada, 0).toString());

            String proveedor = this.cbproveedores.getSelectedItem().toString();

            String fechaString1 = this.txtfechaini.getText();
            long fechaini = Date.parse(fechaString1);
            Date fechaDate1 = new Date(fechaini);

            String fechaString2 = this.txtfechaven.getText();
            long fechaven = Date.parse(fechaString2);
            Date fechaDate2 = new Date(fechaven);

            char formapago = 'D';
            if (this.rbdolares.isSelected()) {
                formapago = 'D';
            } else if (this.rbeuros.isSelected()) {
                formapago = 'E';
            } else if (this.rbotros.isSelected()) {
                formapago = 'O';
            }

            Facturas facturas = new Facturas(nrofactura,proveedor, fechaDate1, fechaDate2, formapago, 'A');

            int decision = JOptionPane.showConfirmDialog(null, "Esta seguro que desea Eliminar esta factura?");

            if (decision == 0) {
                elementosFacturas elementos = new elementosFacturas();
                elementos.eliminarElementosFactura(nrofactura);
                facturas.eliminar();
                this.tableFacturas.setModel(facturas.mostrar());
            }

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int filaSeleccionada = this.tableFacturas.getSelectedRow();
        int nrofactura = Integer.parseInt(this.tableFacturas.getValueAt(filaSeleccionada, 0).toString());
        elementosFacturas elementos = new elementosFacturas();
        JOptionPane.showMessageDialog(null, elementos.MostrarFactura(nrofactura));

    }//GEN-LAST:event_jButton7ActionPerformed

    private void tableFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFacturasMouseClicked

        int filaSeleccionada = this.tableFacturas.rowAtPoint(evt.getPoint());
        this.txtfechaini.setText(this.tableFacturas.getValueAt(filaSeleccionada, 1).toString());
        this.txtfechaven.setText(this.tableFacturas.getValueAt(filaSeleccionada, 2).toString());
        if (this.tableFacturas.getValueAt(filaSeleccionada, 3).toString().charAt(0) == 'D') {
            this.rbdolares.setSelected(true);
        } else if (this.tableFacturas.getValueAt(filaSeleccionada, 3).toString().charAt(0) == 'E') {
            this.rbeuros.setSelected(true);
        } else if (this.tableFacturas.getValueAt(filaSeleccionada, 3).toString().charAt(0) == 'O') {
            this.rbotros.setSelected(true);
        }
        this.cbproveedores.setSelectedItem(this.tableFacturas.getValueAt(filaSeleccionada, 5).toString());


    }//GEN-LAST:event_tableFacturasMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int filaSeleccionada = this.tableFacturas.getSelectedRow();
        int nrofactura = Integer.parseInt(this.tableFacturas.getValueAt(filaSeleccionada, 0).toString());
        this.dispose();
        ArticulosFactura artfac = new ArticulosFactura(nrofactura);
        Principal.desktop.add(artfac);
        artfac.show();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpago;
    private javax.swing.JComboBox cbproveedores;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbdolares;
    private javax.swing.JRadioButton rbeuros;
    private javax.swing.JRadioButton rbotros;
    private javax.swing.JTable tableFacturas;
    private javax.swing.JFormattedTextField txtfechaini;
    private javax.swing.JFormattedTextField txtfechaven;
    // End of variables declaration//GEN-END:variables
}
